### ISSUE TITLE
Create Account -> User not found

### ISSUE THREAD

**Issue by EikeStein** [CodeDefenders/CodeDefenders#15]
After creating a new user on the https://code-defenders.org/ website it's not possible to log-in. The error says "User not found or password incorrect".

**Comment by ein-stein-chen** [comment]
Did try to log in with your email?  
AFAIK it only works with the username and not the email address.

**Comment by EikeStein** [comment]
@ein-stein-chen I tried both. But the account creation happened less than an hour ago. Maybe it just takes longer?

**Comment by ein-stein-chen** [comment]
Normally account creation shouldn't take longer than a few seconds.

If you try to register again with the same credentials, do you get a message, that those are already in use?

**Comment by EikeStein** [comment]
I tried to create the same user again and got a confirmation message. I also am now able to login. A friend of mine also wasn't able to create an account 1 hours ago, but is able to now as well. Anyway this issue is resolved.
