### ISSUE TITLE
The game doesn't work anymore on code-defenders.org

### ISSUE THREAD

**Issue by azaidman** [CodeDefenders/CodeDefenders#16]
I cannot log in with my existing credentials.

I cannot create a new user.

**Comment by ein-stein-chen** [comment]
I can not reproduce this issue.  
Neither the failed login with existing credentials nor the failure to create a new user.

Did you get a confirmation message when creating the new user?  
Did you get any error messages? (Some could be printed to the browser console log)

Did you try again after some time? 
In #15 the issue didn't occure some hours later.

**Comment by azaidman** [comment]
I've asked a colleague who never before tried code defenders to create a login and try to log in... no success :(

**Comment by gofraser** [comment]
I can log in with my existing credentials, and I can create new users. Can you give us an example username for which logging in doesn't work?

**Comment by azaidman** [comment]
Thanks for the quick reaction @gofraser !

I created an account some time ago that I successfully used like 2-3 years ago, that would be "azaidman". Since then, I've also tried with "andyzaidman" and just a few minutes ago "andyzaidmanTUD"...

**Comment by gofraser** [comment]
Hm, I can't see any of these users in the DB (although there are plenty of folks from Delft).

When you try to create an account, do you get the message "Your user has been created. You can login now."?

**Comment by gofraser** [comment]
Just do double check: You are trying this on our public demo machine at code-defenders.org and not on a local installation at Delft, right?

**Comment by azaidman** [comment]
And now it does work! I just created "azaidman2". 
(yes, I am trying the public demo, not a local installation)

Thank you!!! 🙏

**Comment by gofraser** [comment]
OK, no idea what was wrong since we can't even see your failed attempts in the access logs....but glad to see it's solved.
