### ISSUE TITLE
Puzzles Missing JUnit Libraries

### ISSUE THREAD

**Issue by jdehlinger** [CodeDefenders/CodeDefenders#34]
Puzzles seem to be broken and won't compile when tests are required because of missing JUnit library references, see below. Problem repeated on multiple puzzles, multiple users, different computers. 

<img width="686" alt="Screenshot 2023-11-05 at 9 12 05 PM" src="https://github.com/CodeDefenders/CodeDefenders/assets/4109288/7e596abc-db2c-41c5-b310-fb9f0c3f10dd">

**Comment by timlg07** [comment]
Does this only occur with puzzles or with all game types?

**Comment by jdehlinger** [comment]
> Does this only occur with puzzles or with all game types?

It also occurs in created Melee games acting as Defender.

**Comment by ein-stein-chen** [comment]
Do you deploy/run Code Defenders with the container images or a standalone Tomcat server or another way?

Did you execute the [`setup.sh`](https://github.com/CodeDefenders/CodeDefenders/blob/master/installation/setup.sh) script?

It sounds like you are missing all the dependency jars.
Those are installed/downloaded when the `setup.sh` script is executed (through [maven in line 109](https://github.com/CodeDefenders/CodeDefenders/blob/master/installation/setup.sh#L109)).  
See also: README.md on [executing the `setup.sh` script](https://github.com/CodeDefenders/CodeDefenders#create-the-datadir-and-run-the-installation-script) and [creating the configuration](https://github.com/CodeDefenders/CodeDefenders#modify-the-configuration).

**Comment by ein-stein-chen** [comment]
Ah, you might have experienced this with the public-hosted instance on code-defenders.org.

Thanks for the report, this should be fixed now :sweat_smile:!

**Comment by jdehlinger** [comment]
> Ah, you might have experienced this with the public-hosted instance on code-defenders.org.
> 
> Thanks for the report, this should be fixed now 😅!

Sorry for not getting back soon - yes, it was the public-hosted instance and thanks for fixing it. :)

**Comment by Timothy-Bowers1** [comment]
There may be a problem with the libraries again in the public-hosted instance on code-defenders.org. My code is not compiling.
